version: 0.1
phases:
  pre_build:
    commands:
      - node --version
      - npm --version
      - apt-get update
      - apt-get install -y curl
      - mkdir .nvm
      - export NVM_DIR=".nvm"
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | PROFILE="/dev/null" bash
      - . .nvm/nvm.sh
      - nvm install --lts=Dubnium
      - node --version
      - npm --version
      - npm install
  build:
    commands:
      - ls -la node_modules/
artifacts:
  files:
    - .nvm/**/*
    - 'node_modules/**/*'
  discard-paths: no
