version: 0.1
phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y curl
      - mkdir .nvm
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | PROFILE="/dev/null" NVM_DIR=".nvm" bash
      - bash -c 'export NVM_DIR=.nvm; source .nvm/nvm.sh; nvm install --lts="Dubnium"'
      - bash -c 'export NVM_DIR=.nvm; source .nvm/nvm.sh; node --version'
      - bash -c 'export NVM_DIR=.nvm; source .nvm/nvm.sh; npm --version'
      - bash -c 'export NVM_DIR=.nvm; source .nvm/nvm.sh; npm install'
      - npm --version
  build:
    commands:
      - ls -la node_modules/
artifacts:
  files:
    - .nvm/**/*
    - 'node_modules/**/*'
  discard-paths: no
