version: 0.1
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ls -la node_modules/
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: node_modules
