version: 0.1
phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y curl
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt-get install -y nodejs
      - node --version
      - npm --version
      - which node
      - which npm
  build:
    commands:
      - npm install
      - ls -la node_modules/
artifacts:
  files:
    - 'node_modules/**/*'
  discard-paths: no
